/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/StudioBack.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function StudioBack(props) {
  const { nodes, materials } = useGLTF('models/StudioBack.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-9.676, 5.746, -4.995]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[2.435, 2.435, 2.466]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, -0.799, 9.45]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.baza_lcd_0.geometry} material={materials.material} />
            <mesh geometry={nodes.baza_Material015_0.geometry} material={materials['Material.015']} />
          </group>
          <group position={[-8.998, -0.259, 8.801]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0001'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0002'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0003'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0004'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0005'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0006'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0007'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0008'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0009'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0010'].geometry} material={materials['Material.026']} />
            <mesh geometry={nodes['BIGTREETECH_SKR_2-3D__Material026_0011'].geometry} material={materials['Material.026']} />
          </group>
          <group position={[4.792, -5.221, 19.07]} scale={0.1}>
            <mesh geometry={nodes.BUTTON_Material004_0.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.BUTTON_Material_0.geometry} material={materials.Material_0} />
          </group>
          <group position={[0, 19.251, 3.016]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={100}>
            <mesh geometry={nodes.lead_Material036_0.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.lead_Material036_0001.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.lead_Material036_0002.geometry} material={materials['Material.036']} />
            <mesh geometry={nodes.lead_Material036_0003.geometry} material={materials['Material.036']} />
          </group>
          <group position={[0, 22.782, 0.714]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={125}>
            <mesh geometry={nodes.mgn12h_capac_0.geometry} material={materials.capac} />
            <mesh geometry={nodes.mgn12h_Material001_0.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.mgn12h_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.mgn12h_suruburi_0.geometry} material={materials.suruburi} />
          </group>
          <group position={[0, 22.569, 10.246]} rotation={[-Math.PI / 2, 0, 0]} scale={0.132}>
            <mesh geometry={nodes.nut_Material013_0.geometry} material={materials['Material.013']} />
            <mesh geometry={nodes.nut_Material014_0.geometry} material={materials['Material.014']} />
          </group>
          <group position={[3.677, -4.349, -1.728]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.priza_Material016_0.geometry} material={materials['Material.016']} />
            <mesh geometry={nodes.priza_Material017_0.geometry} material={materials['Material.017']} />
          </group>
          <group position={[5.963, 6.758, 1.72]} scale={3.172}>
            <mesh geometry={nodes.vent_Material033_0.geometry} material={materials['Material.033']} />
            <mesh geometry={nodes.vent_Material033_0001.geometry} material={materials['Material.033']} />
            <mesh geometry={nodes.vent_Material033_0002.geometry} material={materials['Material.033']} />
            <mesh geometry={nodes.vent_Material033_0003.geometry} material={materials['Material.033']} />
            <mesh geometry={nodes.vent_Material033_0004.geometry} material={materials['Material.033']} />
          </group>
          <mesh geometry={nodes['50mm_Fan_Grid_Material022_0'].geometry} material={materials['Material.022']} position={[5.954, 8.351, 1.745]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.bolt_Material031_0.geometry} material={materials['Material.031']} position={[0, 20.706, 10.457]} rotation={[Math.PI / 2, 0, Math.PI]} scale={-100} />
          <mesh geometry={nodes.capac_Material029_0.geometry} material={materials['Material.029']} position={[0, 18.749, 9.45]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.coupling__8mm_Material038_0.geometry} material={materials['Material.038']} position={[0, 6.513, 3.032]} rotation={[-Math.PI / 2, 0, 0.742]} scale={100} />
          <mesh geometry={nodes.FEP_Material032_0.geometry} material={materials['Material.032']} position={[0, 7.694, 10.351]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.int__0.geometry} material={materials.int__0} position={[0.793, -3.069, 9.449]} rotation={[-Math.PI / 2, 0, 0]} scale={8.171} />
          <mesh geometry={nodes.PICIOARE_Material034_0.geometry} material={materials['Material.034']} position={[0, -7.864, 9.449]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.sensor_Material037_0.geometry} material={materials['Material.037']} position={[2.336, 6.853, 3.016]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.sina_Material035_0.geometry} material={materials['Material.035']} position={[0.004, 20.021, -0.009]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 88.426]} />
          <mesh geometry={nodes.structura_Material030_0.geometry} material={materials['Material.030']} position={[0, 30.901, 2]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-9.303, 5.669, -3.932]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.731, 0.731, 0.741]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.376, 0.276, 0.02]} scale={0.379}>
            <group position={[0.952, -0.426, -1.171]} rotation={[Math.PI, -1.464, Math.PI]} scale={0.007}>
              <mesh geometry={nodes.Object_13.geometry} material={materials.Bolts} position={[0, 0, -0.001]} />
            </group>
            <group position={[0.965, -0.426, 0.303]} scale={0.007}>
              <mesh geometry={nodes.Object_19.geometry} material={materials.Bolts} position={[0, 0, 0]} />
            </group>
            <group position={[1.156, -0.426, -0.363]} rotation={[Math.PI, -1.464, Math.PI]} scale={0.007}>
              <mesh geometry={nodes.Object_21.geometry} material={materials.Bolts} position={[0, 0, -0.001]} />
            </group>
            <group position={[0.261, -0.426, 1.064]} scale={0.007}>
              <mesh geometry={nodes.Object_33.geometry} material={materials.Bolts} position={[0, 0, 0]} />
            </group>
            <group position={[-0.702, -0.426, 1.064]} scale={0.007}>
              <mesh geometry={nodes.Object_35.geometry} material={materials.Bolts} position={[0, 0, 0]} />
            </group>
            <group position={[-0.484, -0.555, 1.227]} rotation={[Math.PI / 2, 0, 0]} scale={0.007}>
              <mesh geometry={nodes.Object_41.geometry} material={materials.material_0} position={[0, 0, 0]} />
            </group>
            <group position={[-0.484, -0.899, 1.227]} rotation={[Math.PI / 2, 0, 0]} scale={0.007}>
              <mesh geometry={nodes.Object_43.geometry} material={materials.material_0} position={[0, 0, 0]} />
            </group>
            <group position={[-0.13, -0.495, 1.568]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_49.geometry} material={materials.material_0} position={[0, 0, 0]} />
            </group>
            <group position={[-0.13, -0.824, 1.566]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_51.geometry} material={materials.material_0} position={[0, 0, 0]} />
            </group>
            <group position={[-0.13, -0.495, 1.467]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_53.geometry} material={materials.material_0} position={[0, 0, 0]} />
            </group>
            <group position={[-0.13, -0.824, 1.466]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_55.geometry} material={materials.material_0} position={[0, 0, 0]} />
            </group>
            <group position={[-0.368, 1.234, 0.009]} rotation={[0, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_61.geometry} material={materials.Bolts} position={[0, 0, 0]} />
            </group>
            <group position={[-0.368, 1.009, 0.009]} rotation={[0, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_63.geometry} material={materials.Bolts} position={[0, 0, 0]} />
            </group>
            <group position={[-0.08, -0.469, -1.554]} rotation={[-1.678, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_67.geometry} material={materials.Bolts} position={[0, 0, 0]} />
            </group>
            <group position={[-0.08, -0.469, -1.668]} rotation={[-1.678, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_71.geometry} material={materials.Bolts} position={[0, 0, 0]} />
            </group>
            <group position={[-0.731, 1.1, -1.155]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.008}>
              <mesh geometry={nodes.Object_81.geometry} material={materials['metal.002']} position={[0, 0, -0.001]} />
            </group>
            <group position={[-0.731, 0.789, -1.155]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.008}>
              <mesh geometry={nodes.Object_85.geometry} material={materials['metal.002']} position={[0, 0, -0.001]} />
            </group>
            <group position={[-0.092, -0.868, 1.591]} rotation={[0, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_87.geometry} material={materials.Bolts} position={[0, 0.001, 0]} />
            </group>
            <group position={[-0.092, -0.481, 1.591]} rotation={[0, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_89.geometry} material={materials.Bolts} position={[0, 0.001, 0]} />
            </group>
            <group position={[-0.092, -0.868, 1.484]} rotation={[0, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_91.geometry} material={materials.Bolts} position={[0, 0.001, 0]} />
            </group>
            <group position={[-0.092, -0.481, 1.484]} rotation={[0, 0, -Math.PI / 2]} scale={0.007}>
              <mesh geometry={nodes.Object_93.geometry} material={materials.Bolts} position={[0, 0.001, 0]} />
            </group>
            <group position={[-0.408, -0.509, 1.664]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.006}>
              <mesh geometry={nodes.Object_99.geometry} material={materials.Bolts} position={[0, 0, 0.001]} />
            </group>
            <group position={[-0.408, -0.81, 1.664]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.006}>
              <mesh geometry={nodes.Object_101.geometry} material={materials.Bolts} position={[0, 0, 0.001]} />
            </group>
            <group position={[0.957, -0.426, 1.064]} scale={0.007}>
              <mesh geometry={nodes.Object_9.geometry} material={materials.Bolts} position={[0, 0, 0]} />
            </group>
            <group position={[0.71, -0.425, -0.012]} scale={2.637}>
              <mesh geometry={nodes.Object_119.geometry} material={materials['metal.001']} />
              <mesh geometry={nodes.Object_120.geometry} material={materials['Metal_2.001']} />
            </group>
            <group position={[-0.022, 1.056, -0.386]} rotation={[-1.56, 0.586, -0.006]} scale={1.73}>
              <mesh geometry={nodes.Object_134.geometry} material={materials['Black.001']} />
              <mesh geometry={nodes.Object_135.geometry} material={materials['Black.001']} />
            </group>
            <group position={[-0.284, 2.638, -0.038]} rotation={[0, 0, Math.PI]} scale={-2.637}>
              <mesh geometry={nodes.Object_148.geometry} material={materials['Black.001']} />
              <mesh geometry={nodes.Object_149.geometry} material={materials['metal.002']} />
            </group>
            <group position={[-0.857, 0.944, -1.361]} scale={2.637}>
              <mesh geometry={nodes.Object_155.geometry} material={materials.Black} />
              <mesh geometry={nodes.Object_156.geometry} material={materials.Metal_2} />
            </group>
            <group position={[-0.434, 1.136, 0.223]} scale={2.637}>
              <mesh geometry={nodes.Object_158.geometry} material={materials['Black.002']} />
              <mesh geometry={nodes.Object_159.geometry} material={materials.Warn} />
            </group>
            <group position={[0.988, -0.727, -0.038]} scale={2.637}>
              <mesh geometry={nodes.Object_143.geometry} material={materials['Black.002']} />
              <mesh geometry={nodes.Object_144.geometry} material={materials.Screen} />
            </group>
            <group position={[0.08, -0.394, 0.76]} scale={2.637}>
              <mesh geometry={nodes.Object_173.geometry} material={materials['Black.002']} />
              <mesh geometry={nodes.Object_174.geometry} material={materials['Metal_2.001']} />
            </group>
            <group position={[1.207, -0.216, -2.032]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.826, 1.052, 1.826]}>
              <mesh geometry={nodes.Object_186.geometry} material={materials['Metal_2.002']} />
              <mesh geometry={nodes.Object_187.geometry} material={materials['Metal_2.002']} />
              <mesh geometry={nodes.Object_188.geometry} material={materials['Metal_2.002']} />
              <mesh geometry={nodes.Object_189.geometry} material={materials['Metal_2.002']} />
              <mesh geometry={nodes.Object_190.geometry} material={materials['Metal_2.002']} />
              <mesh geometry={nodes.Object_191.geometry} material={materials['Metal_2.002']} />
            </group>
            <mesh geometry={nodes.Object_7.geometry} material={materials.wire} position={[-0.27, 1.076, -0.36]} scale={2.637} />
            <mesh geometry={nodes.Object_11.geometry} material={materials.Bolts} position={[1.15, -0.426, 0.765]} scale={0.007} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.Bolts} position={[1.156, -0.426, -0.954]} rotation={[Math.PI, -1.464, Math.PI]} scale={0.007} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.Bolts} position={[1.15, -0.426, 0.441]} scale={0.007} />
            <mesh geometry={nodes.Object_23.geometry} material={materials.Bolts} position={[0.957, -0.426, -0.28]} rotation={[Math.PI, -1.464, Math.PI]} scale={0.007} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.Bolts} position={[0.496, -0.426, 0.303]} scale={0.007} />
            <mesh geometry={nodes.Object_27.geometry} material={materials.Bolts} position={[0.489, -0.426, -0.28]} rotation={[Math.PI, -1.464, Math.PI]} scale={0.007} />
            <mesh geometry={nodes.Object_29.geometry} material={materials.Bolts} position={[-0.755, -0.426, 0.303]} scale={0.007} />
            <mesh geometry={nodes.Object_31.geometry} material={materials.Bolts} position={[-0.763, -0.426, -0.28]} rotation={[Math.PI, -1.464, Math.PI]} scale={0.007} />
            <mesh geometry={nodes.Object_37.geometry} material={materials.Bolts} position={[-0.071, -0.555, 1.227]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
            <mesh geometry={nodes.Object_39.geometry} material={materials.Bolts} position={[-0.071, -0.899, 1.227]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
            <mesh geometry={nodes.Object_45.geometry} material={materials.material_0} position={[-0.456, -0.551, 1.639]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
            <mesh geometry={nodes.Object_47.geometry} material={materials.material_0} position={[-0.455, -0.784, 1.639]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
            <mesh geometry={nodes.Object_57.geometry} material={materials.Bolts} position={[-0.368, 1.234, 0.171]} rotation={[0, 0, -Math.PI / 2]} scale={0.007} />
            <mesh geometry={nodes.Object_59.geometry} material={materials.Bolts} position={[-0.368, 1.009, 0.171]} rotation={[0, 0, -Math.PI / 2]} scale={0.007} />
            <mesh geometry={nodes.Object_65.geometry} material={materials.Bolts} position={[-0.08, -0.046, -1.554]} rotation={[-1.678, 0, -Math.PI / 2]} scale={0.007} />
            <mesh geometry={nodes.Object_69.geometry} material={materials.Bolts} position={[-0.08, -0.046, -1.668]} rotation={[-1.678, 0, -Math.PI / 2]} scale={0.007} />
            <mesh geometry={nodes.Object_73.geometry} material={materials.Bolts} position={[1.156, 0.107, -1.767]} rotation={[-Math.PI / 2, 0.107, Math.PI]} scale={0.007} />
            <mesh geometry={nodes.Object_75.geometry} material={materials.Bolts} position={[1.274, 0.107, -1.767]} rotation={[-Math.PI / 2, 0.107, Math.PI]} scale={0.007} />
            <mesh geometry={nodes.Object_77.geometry} material={materials.Bolts} position={[-0.401, 0.807, 0.419]} rotation={[Math.PI / 2, 0, 0]} scale={0.007} />
            <mesh geometry={nodes.Object_79.geometry} material={materials['metal.002']} position={[-0.988, 1.1, -1.155]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.008} />
            <mesh geometry={nodes.Object_83.geometry} material={materials['metal.002']} position={[-0.988, 0.789, -1.155]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.008} />
            <mesh geometry={nodes.Object_95.geometry} material={materials.Bolts} position={[-0.335, -0.509, 1.664]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.006} />
            <mesh geometry={nodes.Object_97.geometry} material={materials.Bolts} position={[-0.335, -0.81, 1.664]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.006} />
            <mesh geometry={nodes.Object_103.geometry} material={materials.Bolts} position={[-0.342, -0.336, 1.667]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.008} />
            <mesh geometry={nodes.Object_105.geometry} material={materials.Bolts} position={[-0.342, -0.261, 1.667]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={0.008} />
            <mesh geometry={nodes.Object_109.geometry} material={materials.Black} position={[1.14, -0.427, -0.636]} scale={3.134} />
            <mesh geometry={nodes.Object_111.geometry} material={materials.Black} position={[-1.236, -0.427, 0.591]} scale={3.134} />
            <mesh geometry={nodes.Object_113.geometry} material={materials.Black} position={[-1.236, -0.427, -0.636]} scale={3.134} />
            <mesh geometry={nodes.Object_115.geometry} material={materials.metal} position={[-0.048, -0.337, 0.592]} scale={2.637} />
            <mesh geometry={nodes.Object_117.geometry} material={materials.metal} position={[-0.048, -0.337, -0.636]} scale={2.637} />
            <mesh geometry={nodes.Object_122.geometry} material={materials.rubber} position={[0.71, -0.425, -0.012]} rotation={[0, 1.571, 0]} scale={2.637} />
            <mesh geometry={nodes.Object_124.geometry} material={materials.material_0} position={[-1.224, -0.425, -0.012]} scale={2.637} />
            <mesh geometry={nodes.Object_126.geometry} material={materials.metal} position={[-0.434, 1.137, -1.331]} scale={2.637} />
            <mesh geometry={nodes.Object_128.geometry} material={materials.Black} position={[-0.05, -0.163, -1.413]} scale={[0.096, 0.109, 0.096]} />
            <mesh geometry={nodes.Object_130.geometry} material={materials.material_0} position={[0.262, -0.043, -1.2]} scale={[0.057, 0.065, 0.057]} />
            <mesh geometry={nodes.Object_132.geometry} material={materials['Black.001']} position={[1.207, -0.216, -2.019]} scale={2.637} />
            <mesh geometry={nodes.Object_137.geometry} material={materials.material_0} position={[-0.265, 2.585, -0.825]} rotation={[Math.PI / 2, 0, 0]} scale={0.31} />
            <mesh geometry={nodes.Object_139.geometry} material={materials['Black.002']} position={[-0.262, 1.012, 0.055]} scale={2.637} />
            <mesh geometry={nodes.Object_141.geometry} material={materials.Black} position={[-0.885, 1.207, -1.301]} scale={2.637} />
            <mesh geometry={nodes.Object_107.geometry} material={materials.Black} position={[1.14, -0.427, 0.591]} scale={3.134} />
            <mesh geometry={nodes.Object_146.geometry} material={materials.Black} position={[-0.284, -0.728, 1.219]} scale={2.637} />
            <mesh geometry={nodes.Object_151.geometry} material={materials.Metal_2} position={[-0.033, -0.151, -1.213]} scale={[0.255, 0.13, 0.255]} />
            <mesh geometry={nodes.Object_153.geometry} material={materials.Black} position={[-0.284, -0.728, 1.219]} scale={2.637} />
            <mesh geometry={nodes.Object_161.geometry} material={materials.Eye_sockets} position={[1.534, -0.702, -0.885]} rotation={[0, 0, 0.709]} scale={[0.023, 0.561, 0.023]} />
            <mesh geometry={nodes.Object_163.geometry} material={materials['Black.002']} position={[-0.373, -0.661, 1.655]} scale={[0.22, 0.595, 0.031]} />
            <mesh geometry={nodes.Object_167.geometry} material={materials.metal} position={[-0.287, 1.222, -1.419]} scale={[0.109, 4.978, 0.109]} />
            <mesh geometry={nodes.Object_169.geometry} material={materials.metal} position={[-0.283, 1.239, -1.436]} scale={2.637} />
            <mesh geometry={nodes.Object_171.geometry} material={materials.metal} position={[-0.283, 0.613, -1.436]} scale={2.637} />
            <mesh geometry={nodes.Object_165.geometry} material={materials.material_0} position={[-1.236, -0.445, 0.593]} scale={2.637} />
            <mesh geometry={nodes.Object_176.geometry} material={materials['Material.002']} position={[-0.022, 0.975, 0.036]} scale={0.094} />
            <mesh geometry={nodes.Object_180.geometry} material={materials['Black.002']} position={[1.207, -0.216, -1.774]} scale={3.458} />
            <mesh geometry={nodes.Object_178.geometry} material={materials.Black} position={[-0.092, -0.245, -1.713]} rotation={[0, 0, -Math.PI / 2]} scale={0.824} />
            <mesh geometry={nodes.Object_182.geometry} material={materials.White} position={[-0.093, 2.616, 0.687]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={0.305} />
            <mesh geometry={nodes.Object_184.geometry} material={materials.Eye_sockets} position={[1.625, -0.817, -0.885]} rotation={[Math.PI / 2, 0.71, -Math.PI / 2]} scale={0.581} />
            <mesh geometry={nodes.Object_193.geometry} material={materials['metal.001']} position={[-0.15, 0.094, -1.413]} scale={[0.044, 0.051, 0.044]} />
          </group>
        </group>
      </group>
      <group position={[-6.442, 0.288, -5.945]} rotation={[-Math.PI / 2, 0, 1.598]} scale={[0.015, 0.015, 0.016]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_11001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_13001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_15001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_17001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_19001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_2.geometry} material={materials.wire_027177148} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_21001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_23001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_25001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_27001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_29001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_30.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_31001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_33001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_35001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_37001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_38.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_39001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.wire_153228153} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_41001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_43001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_45001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_47001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_49001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.wire_006135113} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_51001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_53001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_55001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_56.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_57001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_58.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_59001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.wire_006135113} />
        <mesh geometry={nodes.Object_60.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_61001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_62.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_63001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_64.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_65001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_66.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_67001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_68.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_69001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_7001.geometry} material={materials.wire_006135113} />
        <mesh geometry={nodes.Object_70.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_71001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_72.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_73001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_74.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Object_75001.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Object_76.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Object_77001.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Object_78.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Object_79001.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.wire_006135113} />
        <mesh geometry={nodes.Object_80.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Object_81001.geometry} material={materials.wire_008110135} />
        <mesh geometry={nodes.Object_82.geometry} material={materials.wire_027177027} />
        <mesh geometry={nodes.Object_83001.geometry} material={materials.wire_027177027} />
        <mesh geometry={nodes.Object_84.geometry} material={materials.wire_153228184} />
        <mesh geometry={nodes.Object_85001.geometry} material={materials.wire_153228184} />
        <mesh geometry={nodes.Object_86.geometry} material={materials.wire_176026026} />
        <mesh geometry={nodes.Object_87001.geometry} material={materials.wire_228153184} />
        <mesh geometry={nodes.Object_88.geometry} material={materials.wire_228153184} />
        <mesh geometry={nodes.Object_89001.geometry} material={materials.wire_228153184} />
        <mesh geometry={nodes.Object_9001.geometry} material={materials.wire_008008136} />
        <mesh geometry={nodes.Object_90.geometry} material={materials.wire_228153184} />
      </group>
      <group position={[-4.663, 0.159, -2.79]} rotation={[-Math.PI, 0.032, -Math.PI]} scale={[1.792, 1.815, 1.792]}>
        <group scale={0.01}>
          <mesh geometry={nodes.body_main_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[0, 64.355, 0]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={100} />
          <mesh geometry={nodes.Circle002_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[-0.594, 28.162, 5.222]} scale={100} />
          <mesh geometry={nodes.Cube001_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-46.643, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube002_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-38.459, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube003_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-54.768, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube004_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-53.627, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube005_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-37.318, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube006_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-30.333, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube007_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-22.159, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube008_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-21.017, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube009_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-14.033, 70.379, 2.932]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube010_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-5.857, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube011_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-4.716, 70.379, 2.932]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube012_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[2.268, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube013_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[10.451, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube014_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[11.593, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube015_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[18.577, 70.379, 2.932]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube016_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[26.76, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube017_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[27.901, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube018_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[34.886, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube019_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[43.047, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube020_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[44.188, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube021_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[51.172, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube022_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-59.422, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube023_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-58.28, 70.379, 2.933]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube024_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[59.396, 68.549, 5.294]} rotation={[-Math.PI / 2, 0, 0]} scale={[103.823, 100.534, 100]} />
          <mesh geometry={nodes.Cube028_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[0, 28.62, 6.533]} rotation={[Math.PI / 2, -0.595, -Math.PI]} scale={100} />
          <mesh geometry={nodes.Cube029_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[0, 28.62, 3.861]} rotation={[-Math.PI / 2, -0.595, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[-40.416, 55.96, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder001_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[2.004, 30.104, 2.334]} rotation={[Math.PI, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cylinder002_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[2.004, 30.104, 5.486]} scale={100} />
          <mesh geometry={nodes.jack_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[-24.957, 59.034, -8.644]} scale={100} />
          <mesh geometry={nodes.light_light_0.geometry} material={materials['light.001']} position={[-59.904, 71.376, -4.464]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.pedal_btm_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[16.739, 1.253, 6.186]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.pedal_top_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[16.739, 1.253, 6.186]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.power_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-58.922, 71.417, -4.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.select_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-48.967, 71.417, -4.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Sphere_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[0, 28.62, 2.183]} rotation={[-Math.PI, 0, 0]} scale={100} />
          <mesh geometry={nodes.volume_KeyboardMaterial_0.geometry} material={materials['KeyboardMaterial.001']} position={[-52.86, 71.417, -4.482]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.wire_StandMaterial_0.geometry} material={materials['StandMaterial.001']} position={[16.739, 1.069, 1.851]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-2.163, 0.146, -6.455]} scale={[0.987, 1, 0.987]}>
        <mesh geometry={nodes.group_pasted__pCube121.geometry} material={materials['lambert4SG.001']} />
        <mesh geometry={nodes.group_pasted__pCube124.geometry} material={materials['Material #9672.002']} />
        <mesh geometry={nodes.group_pasted__pCube129.geometry} material={materials['aiStandardSurface6SG.001']} />
        <mesh geometry={nodes.group_pasted__polySurface158.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.group_pasted__polySurface158001.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.group_pasted__polySurface182_polySurface5937.geometry} material={materials['Black Painted Wood']} />
        <mesh geometry={nodes.group_pasted__polySurface51_pasted__polySurface582.geometry} material={materials['Wood Black UA']} position={[-7.417, 5.078, 2.053]} scale={1.208} />
        <mesh geometry={nodes.group_pasted__polySurface578_pasted__polySurface259.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes.group_pasted__polySurface580.geometry} material={materials['tool1SG.002']} />
        <mesh geometry={nodes.group_pasted__polySurface585_polySurface6136.geometry} material={materials['table2SG.001']} position={[-6.042, 4.889, 1.778]} />
        <mesh geometry={nodes.group_pasted__polySurface85.geometry} material={materials['Dark Brown Leather']} />
        <mesh geometry={nodes.group_polySurface117_polySurface2.geometry} material={materials['pasted__aiStandardSurface1SG.002']} />
        <mesh geometry={nodes.group_polySurface6132_pasted__polySurface585.geometry} material={materials['table2SG.001']} position={[-5.544, 4.889, 2.409]} />
        <mesh geometry={nodes.group_switch1polySurface1.geometry} material={materials['initialShadingGroup.003']} />
        <mesh geometry={nodes.group3_pasted__polySurface560_polySurface6190.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.group3_pasted__polySurface560_polySurface6191.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.group3_polySurface6189_pasted__polySurface560.geometry} material={materials['lambert6SG.001']} />
        <mesh geometry={nodes.group_pasted__pCube2_polySurface560.geometry} material={materials['initialShadingGroup.003']} position={[-0.151, 0, 1.565]} scale={[1, 1, 0.65]} />
        <mesh geometry={nodes.group_pasted__pCube2_polySurface561.geometry} material={materials['initialShadingGroup.003']} position={[-0.151, 0, 0.876]} scale={[1, 1, 1.094]} />
        <mesh geometry={nodes.LampLight_Base_polySurface116_polySurface131.geometry} material={materials['aiStandardSurface4SG.002']} />
        <mesh geometry={nodes.Lampshade_holder_polySurface130_polySurface116.geometry} material={materials['bedSG.002']} />
        <mesh geometry={nodes.MainWall.geometry} material={materials['Material #9672.002']} />
        <mesh geometry={nodes.ObjStandpCube2_group_pasted__pasted__polySurface70_pasted__gro.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.ObjStandpCube3_group_pasted__pasted__polySurface70_pasted__gro.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.ObjStandpCube4_group_pasted__pasted__polySurface70_pasted__gro.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.ObjStandpCube5_group_pasted__pasted__polySurface70_pasted__gro.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.ObjStandpSphere1_group_pasted__pasted__polySurface70_pasted__g.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.ObjStandpSphere1_group_pasted__polySurface580.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.ObjStandTrim_Char_V_1_1_group_pasted__pasted__polySurface70_pa.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.pasted__polySurface253_group3.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.pasted__pPlane1_group.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.pCube16.geometry} material={materials['Architectural Glass.001']} />
        <mesh geometry={nodes.pCube17.geometry} material={materials['Architectural Glass.001']} />
        <mesh geometry={nodes.pCube18.geometry} material={materials['Architectural Glass.001']} />
        <mesh geometry={nodes.pCube19.geometry} material={materials['Architectural Glass.001']} />
        <mesh geometry={nodes.pCube2.geometry} material={materials['Architectural Glass.001']} />
        <mesh geometry={nodes.pCube57.geometry} material={materials['red_l2SG.003']} />
        <mesh geometry={nodes.pCube58.geometry} material={materials['pillowSG.003']} />
        <mesh geometry={nodes.pCube59.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.pCube60.geometry} material={materials['red_l2SG.003']} />
        <mesh geometry={nodes.pCube61.geometry} material={materials['pillowSG.003']} />
        <mesh geometry={nodes.pCube62.geometry} material={materials['bedSG.002']} />
        <mesh geometry={nodes.pCube63.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.pCube75_polySurface6301.geometry} material={materials['pillowSG.003']} />
        <mesh geometry={nodes.pCube75_polySurface6302.geometry} material={materials['red_l2SG.003']} />
        <mesh geometry={nodes.pCube80.geometry} material={materials['flr3SG.001']} />
        <mesh geometry={nodes.pCube84.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes.pCube85.geometry} material={materials['initialShadingGroup.003']} />
        <mesh geometry={nodes.pCube87_polySurface6305.geometry} material={materials['pillowSG.003']} />
        <mesh geometry={nodes.pCube87_polySurface6306.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.pCube87_polySurface6307.geometry} material={materials['yellow1SG.003']} />
        <mesh geometry={nodes.pCube94_polySurface6315.geometry} material={materials['initialShadingGroup.003']} />
        <mesh geometry={nodes.pCube94_polySurface6316.geometry} material={materials['initialShadingGroup.003']} />
        <mesh geometry={nodes.pCube94_polySurface6317.geometry} material={materials['bedSG.002']} />
        <mesh geometry={nodes.pCube94_polySurface6318.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.pCube94_polySurface6319.geometry} material={materials['initialShadingGroup.003']} />
        <mesh geometry={nodes.pCube95_polySurface6309.geometry} material={materials['initialShadingGroup.003']} />
        <mesh geometry={nodes.pCube95_polySurface6310.geometry} material={materials['red_l2SG.003']} />
        <mesh geometry={nodes.pCube95_polySurface6311.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.pCube95_polySurface6312.geometry} material={materials['red_l2SG.003']} />
        <mesh geometry={nodes.pCube95_polySurface6313.geometry} material={materials['bedSG.002']} />
        <mesh geometry={nodes.pCylinder62.geometry} material={materials['Hammered Bronze']} />
        <mesh geometry={nodes.pCylinder75.geometry} material={materials['aiStandardSurface4SG.003']} />
        <mesh geometry={nodes.pDisc1.geometry} material={materials['Rug Velvet']} />
        <mesh geometry={nodes.polySurface122.geometry} material={materials['aiStandardSurface4SG.002']} />
        <mesh geometry={nodes.polySurface123_polySurface39.geometry} material={materials['pasted__aiStandardSurface1SG.002']} />
        <mesh geometry={nodes.polySurface220_group_pasted__pCube2.geometry} material={materials['3D waves wall tile']} />
        <mesh geometry={nodes.polySurface234_polySurface6192.geometry} material={materials['wallSG.002']} />
        <mesh geometry={nodes.polySurface5670.geometry} material={materials['initialShadingGroup.003']} />
        <mesh geometry={nodes.polySurface5686_polySurface5757.geometry} material={materials['initialShadingGroup.002']} position={[4.096, 0, 4.81]} rotation={[-Math.PI, 0.002, -Math.PI]} />
        <mesh geometry={nodes.polySurface5686_polySurface5758.geometry} material={materials['initialShadingGroup.002']} position={[4.096, 0, 4.81]} rotation={[-Math.PI, 0.002, -Math.PI]} />
        <mesh geometry={nodes.polySurface5703_polySurface5696.geometry} material={materials['pasted__aiStandardSurface1SG.003']} />
        <mesh geometry={nodes.polySurface5704_polySurface5697.geometry} material={materials['pasted__aiStandardSurface1SG.003']} />
        <mesh geometry={nodes.polySurface5934.geometry} material={materials['aiStandardSurface4SG.002']} />
        <mesh geometry={nodes.polySurface5936.geometry} material={materials['aiStandardSurface4SG.002']} />
        <mesh geometry={nodes.polySurface5948_polySurface6015.geometry} material={materials['aiStandardSurface1SG.001']} />
        <mesh geometry={nodes.polySurface6014_polySurface5948.geometry} material={materials['aiStandardSurface1SG.001']} />
        <mesh geometry={nodes.polySurface609_polySurface234.geometry} material={nodes.polySurface609_polySurface234.material} />
        <mesh geometry={nodes.polySurface613_polySurface6182.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.polySurface613_polySurface6183.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.polySurface613_polySurface6184.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.polySurface613_polySurface6185.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.polySurface613_polySurface6186.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.polySurface613_polySurface6187.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.polySurface613_polySurface6188.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.polySurface6137.geometry} material={materials['Black Leather']} position={[-5.782, 4.319, 2.091]} />
        <mesh geometry={nodes.polySurface6181_polySurface613.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.polySurface6193_polySurface5637.geometry} material={materials['potSG.001']} />
        <mesh geometry={nodes.polySurface6205.geometry} material={materials['aiStandardSurface9SG.001']} />
        <mesh geometry={nodes.polySurface6300_pCube75.geometry} material={materials['pillowSG.003']} />
        <mesh geometry={nodes.polySurface6304_pCube87.geometry} material={materials['red_l2SG.003']} />
        <mesh geometry={nodes.polySurface6308_pCube95.geometry} material={materials['bedSG.002']} />
        <mesh geometry={nodes.polySurface6314_pCube94.geometry} material={materials['bedSG.002']} />
        <mesh geometry={nodes.polySurface6710.geometry} material={materials['initialShadingGroup.002']} position={[-5.654, 4.734, 2.043]} />
        <mesh geometry={nodes.polySurface843_polySurface813.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes.pSphere1.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes.pSphere2.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes.pSphere3.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes.pSphere4.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes['Studio-Top-Level_FLOOR'].geometry} material={materials.maptexture001} />
        <mesh geometry={nodes['Studio_Lvl1-SideWall'].geometry} material={materials['Architectural Glass.001']} />
        <mesh geometry={nodes.Wardrobe_modular_system_finalCarcass_wardrobe_group_pasted.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.Wardrobe_modular_system_finalCarcass_wardrobe_group_pasted001.geometry} material={materials['aiStandardSurface5SG.002']} />
        <mesh geometry={nodes.Wardrobe_modular_system_finalCarcass_wardrobe_group_pasted__po.geometry} material={materials.maptexture001} />
        <mesh geometry={nodes.WindowFrame.geometry} material={materials['aiStandardSurface5SG.002']} />
        <mesh geometry={nodes.Mesh_689.geometry} material={materials['Black Painted Wood']} />
        <mesh geometry={nodes.Mesh_689_1.geometry} material={nodes.Mesh_689_1.material} />
        <mesh geometry={nodes.Mesh_689_2.geometry} material={nodes.Mesh_689_2.material} />
        <mesh geometry={nodes.Mesh_689_3.geometry} material={nodes.Mesh_689_3.material} />
        <mesh geometry={nodes.Mesh_680.geometry} material={materials['Screen.001']} />
        <mesh geometry={nodes.Mesh_680_1.geometry} material={nodes.Mesh_680_1.material} />
        <mesh geometry={nodes.Mesh_576.geometry} material={materials['tool1SG.003']} />
        <mesh geometry={nodes.Mesh_576_1.geometry} material={materials['com2SG.001']} />
        <mesh geometry={nodes.Mesh_576_2.geometry} material={materials['tool1SG.002']} />
        <mesh geometry={nodes.Mesh_557.geometry} material={materials['pillowSG.002']} />
        <mesh geometry={nodes.Mesh_557_1.geometry} material={materials['bedSG.003']} />
        <mesh geometry={nodes.Mesh_557_2.geometry} material={materials['tool1SG.002']} />
        <mesh geometry={nodes.Mesh_557_3.geometry} material={materials['red_l2SG.002']} />
        <mesh geometry={nodes.Mesh_557_4.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes.Mesh_557_5.geometry} material={materials['bedSG.002']} />
        <mesh geometry={nodes.Mesh_558.geometry} material={materials['yellow1SG.002']} />
        <mesh geometry={nodes.Mesh_558_1.geometry} material={materials['tool1SG.002']} />
        <mesh geometry={nodes.Mesh_558_2.geometry} material={materials['pillowSG.002']} />
        <mesh geometry={nodes.Mesh_558_3.geometry} material={materials['red_l2SG.003']} />
        <mesh geometry={nodes.Mesh_559.geometry} material={materials['red_l2SG.002']} />
        <mesh geometry={nodes.Mesh_559_1.geometry} material={materials['bedSG.003']} />
        <mesh geometry={nodes.Mesh_559_2.geometry} material={materials['pillowSG.002']} />
        <mesh geometry={nodes.Mesh_559_3.geometry} material={materials['tool1SG.002']} />
        <mesh geometry={nodes.Mesh_559_4.geometry} material={materials['initialShadingGroup.002']} />
        <mesh geometry={nodes.Mesh_559_5.geometry} material={materials['bedSG.002']} />
        <mesh geometry={nodes.Mesh_542.geometry} material={materials['aiStandardSurface5SG.002']} />
        <mesh geometry={nodes.Mesh_542_1.geometry} material={materials['window1SG.001']} />
        <mesh geometry={nodes.Mesh_543.geometry} material={materials['aiStandardSurface5SG.002']} />
        <mesh geometry={nodes.Mesh_543_1.geometry} material={materials['window1SG.001']} />
        <mesh geometry={nodes.Mesh_544.geometry} material={materials['window1SG.001']} />
        <mesh geometry={nodes.Mesh_544_1.geometry} material={materials['aiStandardSurface5SG.002']} />
        <mesh geometry={nodes.Mesh_545.geometry} material={materials['window1SG.001']} />
        <mesh geometry={nodes.Mesh_545_1.geometry} material={materials['aiStandardSurface5SG.002']} />
      </group>
      <group position={[-5.808, 0.146, -6.455]} scale={[0.987, 1, 0.987]}>
        <mesh geometry={nodes.polySurface219001.geometry} material={materials['metal2SG.002']} position={[-0.231, 0.707, 1.322]} rotation={[-Math.PI, 0.002, -Math.PI]} />
      </group>
      <group position={[-3.777, 6.78, -9.74]} scale={0.01}>
        <mesh geometry={nodes.Line1789529887001.geometry} material={materials['Material #9674.001']} position={[37.919, 14.83, -168.177]} rotation={[Math.PI / 2, 0, 0]} scale={[2.372, 13.188, 1.544]} />
      </group>
      <group position={[-2.529, 0, -5.389]} rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
        <group position={[-5.2, -1, -0.001]}>
          <mesh geometry={nodes.Object_3001.geometry} material={materials['Material #9674.001']} position={[6.281, 1.321, 1.566]} scale={[0.874, 0.71, 1.033]} />
        </group>
      </group>
      <mesh geometry={nodes.TopLevelWall.geometry} material={materials['Material #9674.001']} position={[-10.155, 6.262, -6.49]} scale={[0.076, 2.118, 4.943]} />
      <mesh geometry={nodes.Curve005.geometry} material={nodes.Curve005.material} position={[-2.156, 3.516, -5.92]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.1} />
      <mesh geometry={nodes.Text008.geometry} material={nodes.Text008.material} position={[-2.155, 3.589, -6.968]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.1} />
      <mesh geometry={nodes.Text009.geometry} material={nodes.Text009.material} position={[-2.155, 3.388, -6.954]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={2.1} />
      <mesh geometry={nodes.Window_Pane.geometry} material={materials['Architectural Glass.001']} position={[1.368, 2.799, -11.43]} scale={[0.608, 0.965, 0.05]} />
      <mesh geometry={nodes.Window_Pane001.geometry} material={materials['Architectural Glass.001']} position={[1.368, 4.894, -11.426]} scale={[0.608, 1.052, 0.055]} />
      <mesh geometry={nodes.Window_Pane002.geometry} material={materials['Architectural Glass.001']} position={[1.368, 7.012, -11.43]} scale={[0.608, 0.972, 0.05]} />
    </group>
  )
}

useGLTF.preload('models/StudioBack.glb')
